name: Deploy

on:
  push:
    branches-ignore:
      - template
  pull_request:
    branches-ignore:
      - template

jobs:
  Deployment:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.7b6ce9e18bae4c09b00fa73aa2387647 }}
      HEROKU_APP_NAME: ${{ secrets.PBP_Syarief }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dpl
      run: gem install dpl
    - name: Install Heroku CLI
      run: wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - name: Deploy to Heroku
      run: dpl --provider=heroku --app=$PBP_Syarief --api-key=$7b6ce9e18bae4c09b00fa73aa2387647
    - name: Run migrations on Heroku
      run: heroku run --app $PBP_Syarief migrate
    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      with:
        initial_status: success
        token: ${{ github.token }}
        target_url: https://${{ secrets.PBP_Syarief }}.herokuapp.com
        environment: production
